# Generated by Django 3.2 on 2023-01-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greatestinvestapp', '0003_client_running_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bonus_balance',
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('transaction_type', models.CharField(blank=True, default='Pending Bonus', max_length=64, null=True)),
                ('amount', models.FloatField(default=0, null=True)),
                ('code', models.CharField(blank=True, max_length=8, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='greatestinvestapp.client')),
            ],
        ),
    ]
